# GitHub Pages Configuration for RackedUp Documentation

# Site settings
title: "RackedUp Help & Documentation"
description: "Complete user guide and documentation for RackedUp - the ultimate gym companion for serious athletes"
url: "https://tshives26.github.io"
baseurl: "/RackedUp"
version: "1.0.0"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "RackedUp Team"
twitter:
  username: "rackedup_app"
  card: "summary_large_image"

# Navigation
navigation:
  - title: "Getting Started"
    url: "#getting-started"
  - title: "Features"
    url: "#core-features"
  - title: "Workout Tracking"
    url: "#workout-tracking"
  - title: "Progress & Analytics"
    url: "#progress--analytics"
  - title: "Programs & Routines"
    url: "#programs--routines"
  - title: "Profile & Settings"
    url: "#profile--settings"
  - title: "Tools & Utilities"
    url: "#tools--utilities"
  - title: "Troubleshooting"
    url: "#troubleshooting"
  - title: "FAQ"
    url: "#faq"
  - title: "Support"
    url: "#contact--support"

# Custom CSS
custom_css:
  - "/assets/css/custom.css"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
